changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Features
      labels:
        - enhancement
        - feature
    - title: Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: Maintenance
      labels:
        - chore
        - dependencies
        - documentation
