pluginGroup=dev.lavalink.bilibili
projectDescription=Bilibili source modules for Lavalink and Lavaplayer
commonArtifactId=bilibili-common
pluginArtifactId=bilibili-plugin
commonDescription=Bilibili source manager for Lavaplayer
pluginDescription=Bilibili source plugin for Lavalink
pluginApiVersion=3.6.1
lavaplayerVersion=1.3.98.4
projectUrl=https://github.com/kyokusakin/bilibili-source
developerId=kyokusakin
developerName=kyokusakin
releaseTagPrefix=bilibili-source-
fallbackSnapshotVersion=dev-SNAPSHOT
kotlin.code.style=official
org.gradle.jvmargs=-Xmx1g -Dfile.encoding=UTF-8
